# ========================
# Basic Site Settings
# ========================
locale                   : "en-US"
site_theme               : "default"
title                    : "Yue Li - Economics"
title_separator          : "-"
name                     : &name "Yue Li"
description              : &description "Personal academic homepage of Yue Li, PhD Candidate in Economics at UCL"
url                      : "https://yueli-econ.github.io" 
baseurl                  : ""
repository               : "yueli-econ/yueli-econ.github.io"

# ========================
# Author Profile
# ========================
author:
  avatar           : "profile.png"
  name             : "Yue Li"
#  pronouns         : "she/her"
  bio              : "Econ Ph.D. Candidate(UCL)"
  location         : "London"
  employer         : "University College London"
  email            : "yue.li.22@ucl.ac.uk"

  # Academic sites
  # googlescholar    : "https://scholar.google.com/"   # replace with your Scholar ID
  # orcid            : "https://orcid.org/"            # replace with your ORCID
  # researchgate     : # optional
  # scopus           : # optional

  # Repositories
  github           : "yueli-econ"

  # Social media
  linkedin         : "yue-li-91a4641a6"
  twitter          : "YueLi58377775" # X / Twitter
  bluesky          : "nkliyue.bsky.social"  

# ========================
# Publications
# ========================
publication_category:
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'
  workingpapers:
    title: 'Working Papers'

# ========================
# Site Settings
# ========================
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

atom_feed:
  hide                   : false
  path                   :

# ========================
# SEO
# ========================
google_site_verification :
# 关键词和描述
keywords:
  - Economics
  - Education
  - Peer Effects
  - Yue Li
  - University College London
  - UCL
  - Oxford

description: "Personal academic homepage of Yue Li, PhD Candidate in Economics at UCL."

# ========================
# Social Sharing
# ========================
# twitter:
#   username               : &twitter "yueli_econ"
# og_image                 :
# og_description           :
# social:
#   type                   : Person
#   name                   : "Yue Li"
#   links:
#     - "https://scholar.google.com/"
#     - "https://github.com/yueli-econ"
#     - "https://www.linkedin.com/in/your-linkedin-id/"

# ========================
# Analytics
# ========================
analytics:
  provider               : "google-analytics-4"
  google:
    tracking_id          : "G-XXXXXXXXXX"   # replace with your GA4 ID

# ========================
# Reading Files
# ========================
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - node_modules
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# ========================
# Conversion
# ========================
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6

# ========================
# Collections
# ========================
collections:
  Research:
    output: true
    permalink: /research/:path/
  Others:
    output: true
    permalink: /others/:path/
# ========================
# Navigation
# ========================
main:
  # - title: "Home"
  #   url: /
  - title: "Research"
    url: /research/
  - title: "Teaching & Service"
    url: /others/

# ========================
# Defaults
# ========================
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: others
    values:
      layout: single
      author_profile: true
      share: true

# ========================
# Sass
# ========================
sass:
  sass_dir: _sass
  style: compressed

# ========================
# Output
# ========================
permalink: /:categories/:title/
timezone: Europe/London

# ========================
# Plugins
# ========================
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
